#!/bin/sh

chmod +x  /etc/init.d/remotewol
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@remotewol[-1]
	add ucitrack remotewol
	set ucitrack.@remotewol[-1].init=remotewol
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
